import pandas as pd
df = pd.read_csv("datasetbank.csv")

print("1.First five Records :")
print(df.head())
print("2.Last five Records :")
print(df.tail())
print("3.Size of the dataset :", df.size)
print("\n4.Dataset shape :", df.shape)
print(df.shape[0])
print(df.shape[1])
print("\n5.List of coloumns :", df.columns)
print("\n6. Axes:", df.axes)
print("\n7. Number of Dimensions:", df.ndim)
print("\n8.Info about the dataset :", df.info())
print("\n9.Statistical Summary :", df.describe())
print("\n10.Number of missing values: ",df.isnull().sum())
print("\n11.Memory used for each coloumn: ", df.memory_usage())
print("\n12. Maximum Values:")
print(df.max(numeric_only=True))
print("\n13. Minimum Values:")
print(df.min(numeric_only=True))
print("\n14. Mean:")
print(df.mean(numeric_only=True))
print("\n15. Median:")
print(df.median(numeric_only=True))
print("\n16. Standard Deviation:")
print(df.std(numeric_only=True))
print("\n17. Random Sample (3 Rows):", df.sample(3))